all: arrayfillerbycolumn arrayfillerbyrow

CFLAGS=-Wall

arrayfillerbycolum: arrayfillerbycolum.o

arrayfillerbyrow: arrayfillerbyrow.o

clean:
	$(RM) arrayfillerbycolum.o arrayfillerbyrow.o \
			arrayfillerbycolumn arrayfillerbyrow
