#!/bin/bash

prefix=https://raw.githubusercontent.com/huichen-cs/OSClassExamples/master/memory/linux/

ptfiles=(pagetable/pagetable.c
	pagetable/countframes
	pagetable/Makefile
	pagetable/pagetable.c)

dlfiles=(dlsharing/Makefile
	dlsharing/vector.h
	dlsharing/driver1.cpp
	dlsharing/driver2.cpp
	dlsharing/vector.cpp)

workdir=$(pwd)
echo "Working in directory $(workdir) ..."

mkdir -p dlsharing
echo "Created ${workdir}/dlsharing ..."
cd dlsharing || exit 1
echo "Entered ${workdir}/dlsharing ..."
for f in "${dlfiles[@]}"; do
	echo -n "downloading ${f} ..."
	if wget -c -q "${prefix}/${f}"; then
		echo "done"
	else
		echo "failed"
	fi
done
echo "Compile the driver1, driver2, driver1dl, and driver2dl programs ..."
make
cd "${workdir}" || exit 1
echo "Returned to ${workdir} ..."

for f in "${ptfiles[@]}"; do
	echo -n "downloading ${f} ..."
	if wget -c -q "${prefix}/${f}"; then
		echo "done"
	else
		echo "failed"
	fi
done

echo "Compile the pagetable program ..."
make

echo "Run the programs ..."
./dlsharing/driver1 &
d1pid=$!
./dlsharing/driver2 &
d2pid=$!

LD_LIBRARY_PATH=./dlsharing ./dlsharing/driver1dl &
d1dlpid=$!
LD_LIBRARY_PATH=./dlsharing ./dlsharing/driver2dl &
d2dlpid=$!

sleep 1
echo "driver1's pid is   ${d1pid}"
echo "driver2's pid is   ${d2pid}"
echo "driver1dl's pid is ${d1dlpid}"
echo "driver2dl's pid is ${d2dlpid}"

echo "You can now use the pagetable program to check their page tables"
